version: "3"

services:
  database:
    image: "postgres:9.6.13"
    environment:
      - POSTGRES_USER=omero
      - POSTGRES_DB=omero
      - POSTGRES_PASSWORD=omero
    networks:
      - omero
    volumes:
      - "database:/var/lib/postgresql/data"

  omero:
    image: openmicroscopy/omero-server:5.5.1
    environment:
      - CONFIG_omero_jvmcfg_heap__size=4g
      - CONFIG_omero_db_host=database
      - CONFIG_omero_db_user=omero
      - CONFIG_omero_db_pass=omero
      - CONFIG_omero_db_name=omero
      - ROOTPASS=omero
    networks:
      - omero
    ports:
      - "4063:4063"
      - "4064:4064"
    volumes:
      - "omero:/OMERO"
      - "./custom_scripts:/opt/omero/server/OMERO.server/lib/scripts/custom_scripts:ro"
      - "/media/nassauvia/1TB/Dundee/OMERO/data:/external_data/test:ro"
  web:
    image: openmicroscopy/omero-web-standalone:5.5.1
    environment:
      - OMEROHOST=omero
      - CONFIG_omero_web_public_enabled=True
      - CONFIG_omero_web_public_user=general_public
      - CONFIG_omero_web_public_password=0p3nD@tA1sa//
      - CONFIG_omero_web_public_url__filter=^/(webadmin/myphoto/|webclient/(?!(script_ui|ome_tiff|figure_script))|webgateway/(?!(archived_files|download_as))|iviewer|api)
      - 'CONFIG_omero_web_login__redirect={"redirect": ["webindex"], "viewname": "load_template", "args":["userdata"], "query_string": "experimenter=-1"}'
    networks:
      - omero
    ports:
      - "4080:4080"
    volumes:
      # web-apps configuration
      - "./web/additional-webapps.omero:/opt/omero/web/config/additional-webapps.omero:ro"

networks:
  omero:

volumes:
  database:
  omero:
